<?php
require_once('mysql_model.php');
require_once('functions.php');

$functions = new LoginHelper();
$sqlConn = new connect();
$sqlConn->dbConnet();

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $message_err = '';
    $email = trim($_POST["email"]);
    $updateDay =  date("Y.m.d",time());
    $checkedResultsArray = $functions->checkRegister(null, $email, null, null);
    if (is_array($checkedResultsArray)) {

        $sql = "SELECT id,username,email,password FROM users WHERE email LIKE '" . $checkedResultsArray[0] . "'";
        $result = $sqlConn->dbConnet()->query($sql);
        $foundElements = $result->fetchAll();
//        echo"<pre>";
//        print_r($foundElements);
//        echo"</pre>";
        if (count($foundElements)>0) {
            $id = $foundElements[0][0];
            $autoGeneratedPasswort = $functions->ranPassword();

            $updateSqul ="UPDATE users SET password = \"$autoGeneratedPasswort\",updated_at = \"$updateDay\" WHERE id LIKE \"$id\" ";

            if( $sqlConn->dbConnet()->query($updateSqul))
            {
                $message_err = "Datensatz erfolgreich aktualisiert<br>";
                $functions->resetPasswortEmail( $foundElements[0][1],$autoGeneratedPasswort);
                $message_err .= "Sie werden eine E-Mail erhalten ";
            }
            else
            {
                //dbConnet()->$php_errormsg i am not shore from that before was $ error and there was an error 
                $message_err = "Fehler beim Aktualisieren des Datensatzes: ".$sqlConn->dbConnet()->$php_errormsg. '<br>';
            }
        }
    } else {
        $message_err = "Überprüfen Sie Ihre E-Mail oder Ihr Passwort oder Falls Sie kein Konto habe Bitte Registrieren Sie Sich   ";
    }

}

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> Reset the Password </title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#03a6f3">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>


<div class="pageContainer" style="width: 100%">
    <section class="vh-100"
             style="background-image: url('https://mdbcdn.b-cdn.net/img/Photos/new-templates/search-box/img7.webp');">
        <div class="container py-5 h-100" style="width: 41%">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col col-xl-10">
                    <div class="card" style="border-radius: 1rem ">
                        <div class="card-body p-4 p-lg-5 text-black">
                            <!--                            <p id ="successMessage">-->
                            <?php //if (isset($_SESSION["successMessage"])) {
                            //                                    echo $_SESSION["successMessage"];
                            //                                    $_SESSION["successMessage"] = '';
                            //                                }?><!--</p>-->
                            <form method="POST" action="<?php echo $_SERVER["PHP_SELF"]; ?>">

                                <div class="d-flex align-items-center mb-3 pb-1">
                                    <span class="h1 fw-bold mb-0">Haben Sie Ihr Passwort vergessen?</span>
                                </div>
                                <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Ändern Sie Ihr Passwort in
                                    drei einfachen Schritten. Dies hilft Ihnen, Ihr Passwort zu sichern!</h5>
                                <ul>
                                    <li> Geben Sie unten Ihre E-Mail-Adresse ein.</li>
                                    <li> Unser System sendet Ihnen einen temporären Link</li>
                                    <li>Verwenden Sie den Link, um Ihr Passwort zurückzusetzen</li>
                                </ul>
                                <div class="form-outline mb-4">
                                    <input type="email" id="form2Example17" class="form-control form-control-lg"
                                           name="email" value=" "/>
                                    <label class="form-label" for="form2Example17" style="font-size: 12px">Geben Sie die
                                        E-Mail-Adresse ein, die Sie bei der Registrierung verwendet haben. Dann senden
                                        wir einen Link per E-Mail an diese Adresse.</label>
                                </div>
                                <div class="pt-1 mb-4">
                                    <button class="btn btn-dark btn-lg btn-block" type="submit" style="background: #adc0c8;border: solid 1px #adc0c8 ">Passwort zurücksetzen</button>
                                </div>

                                <!--                                <a class="small text-muted" href="#!">Ihre Passwort vergessen?</a>-->
                                <p class="mb-5 pb-lg-2" style="color: #393f81;">Haben Sie  Konto? <a
                                        href="./login.php" style="color: #393f81;">zurück zur Anmeldung</a></p>
                                <a href="#!" class="small text-muted">Datenschutz Lesen</a>
                            </form>
                            <br/>
                            <p style="color: #2a2727;"> <?php if (isset($message_err)) {
                                    echo $message_err;
                                } else {
                                    echo " ";
                                } ?> </p>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
</div>